package media.interaktif;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Akun extends javax.swing.JFrame {
    private DefaultTableModel tabmode;
    private ResultSet hasil;

    CRUDakun akun = new CRUDakun();
    
    public Akun() {
        initComponents();
        tampil_database();
        setLocationRelativeTo(null);
    }
    public void tampil_database(){
        Object[]baris = {"nama", "username", "password", "confirm"};
        tabmode = new DefaultTableModel(null, baris);
        tbl_akun.setModel(tabmode);
        try{
            hasil = akun.tampilData();
            while(hasil.next()){
                akun.setnama(hasil.getString("nama"));
                akun.setusername(hasil.getString("username"));
                akun.setPassword(hasil.getString("password"));
                akun.setconfirm(hasil.getString("confirm"));
                String[] data = {akun.getnama(), akun.getusername(), akun.getPassword(), akun.getconfirm()};
                tabmode.addRow(data);
            } 
        } catch(Exception e){
        }
    }
    
    public void reset_text(){
        txt_nama.setText("");
        txt_user.setText("");
        txt_pass.setText("");
        txt_confirm.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    } 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_user = new javax.swing.JTextField();
        txt_pass = new javax.swing.JTextField();
        txt_confirm = new javax.swing.JTextField();
        btn_ubah = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_akun = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nama :");

        jLabel3.setText("Username :");

        jLabel4.setText("Password :");

        jLabel5.setText("Confirm Password :");

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        tbl_akun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama", "Username"
            }
        ));
        tbl_akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_akunMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_akun);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("DATA ADMIN");

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_pass, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_user, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel9)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_reset)
                        .addComponent(btn_hapus))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_simpan)
                        .addComponent(btn_ubah)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        if(txt_nama.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Nama belum diisi!");
            txt_nama.requestFocus();
        }else if(txt_user.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Username belum diisi!");
            txt_user.requestFocus();
        }else if(txt_pass.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Password belum diisi!");
            txt_pass.requestFocus();
        }else if(txt_confirm.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Password belum diisi!");
            txt_confirm.requestFocus();
            
        }else {
            String nama = "", username = "",  pass = "", confirm = "";
            try {
                akun.setnama(txt_nama.getText());
                akun.setusername(txt_user.getText());
                akun.setPassword(txt_pass.getText());
                akun.setconfirm(txt_confirm.getText());
                
                akun.ubahData(akun.getnama(), akun.getusername(), akun.getPassword(), akun.getconfirm());
                
                JOptionPane.showMessageDialog(null, "Data berhasil diubah" , "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal diubah","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }                                     

    }//GEN-LAST:event_btn_ubahActionPerformed
   
    
    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        if(txt_nama.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Nama belum diisi!");
            txt_nama.requestFocus();
        }else if(txt_user.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Username belum diisi!");
            txt_user.requestFocus();
        }else if(txt_pass.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Password belum diisi!");
            txt_pass.requestFocus();
        }else if(txt_confirm.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Password belum diisi!");
            txt_confirm.requestFocus();
        }else {
            String nama = "", username = "", password = "", confirm = "";
            try {
                akun.setnama(txt_nama.getText());
                akun.setusername(txt_user.getText());
                akun.setPassword(txt_pass.getText());
                akun.setconfirm(txt_confirm.getText());
                
                akun.simpanData(akun.getnama(), akun.getusername(), akun.getPassword(), akun.getconfirm());
                
                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan" , "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal tersimpan","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }                                      
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        if(txt_nama.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Nama belum diisi!");
            txt_nama.requestFocus();
        } else {
            if(JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data ini ?",
                    "Warning",2)==JOptionPane.YES_OPTION){
                String nama = "";
                try {
                    akun.setnama(txt_nama.getText());
                    akun.hapusData(akun.getnama());
                    
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus" , "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                    tampil_database();
                    reset_text();
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tbl_akunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_akunMouseClicked
        try {
            int row = tbl_akun.rowAtPoint(evt.getPoint());
            
            String nama = tbl_akun.getValueAt(row, 0).toString();
            String username = tbl_akun.getValueAt(row, 1).toString();
            String password = tbl_akun.getValueAt(row, 2).toString();
            String confirm = tbl_akun.getValueAt(row, 3).toString();
            
            txt_nama.setText(String.valueOf(nama));
            txt_user.setText(String.valueOf(username));
            txt_pass.setText(String.valueOf(password));
            txt_confirm.setText(String.valueOf(confirm));
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_tbl_akunMouseClicked

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset_text();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Beranda_admin n = new Beranda_admin();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Akun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Akun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_akun;
    private javax.swing.JTextField txt_confirm;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
