
package media.interaktif;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Mahasiswa extends javax.swing.JFrame {
    private DefaultTableModel tabmode;
    private ResultSet hasil;
    
    CRUDmhs mhs = new CRUDmhs();
    
    public Mahasiswa(){
        initComponents();
        tampil_database();
        setLocationRelativeTo(null);
    }
    
    public void tampil_database(){
        Object[]baris = {"nim", "nama", "prodi", "angkatan", "off", "pass"};
        tabmode = new DefaultTableModel(null, baris);
        tbl_mhs.setModel(tabmode);
        try{
            hasil = mhs.tampilData();
            while(hasil.next()){
                mhs.setNim(hasil.getString("nim"));
                mhs.setNama(hasil.getString("nama"));
                mhs.setProdi(hasil.getString("prodi"));
                mhs.setAng(hasil.getString("angkatan"));
                mhs.setOff(hasil.getString("off"));
                mhs.setPass(hasil.getString("pass"));
                String[] data = {mhs.getNim(), mhs.getNama(), mhs.getProdi(), mhs.getAng(), mhs.getOff(), mhs.getPass()};
                tabmode.addRow(data);
            } 
        } catch(Exception e){
        }
    }
    
    public void reset_text(){
        txt_nim.setText("");
        txt_nama.setText("");
        txt_prodi.setText("");
        txt_ang.setText("");
        txt_off.setText("");
        txt_pass.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nim = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mhs = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_prodi = new javax.swing.JTextField();
        txt_ang = new javax.swing.JTextField();
        txt_off = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("DAFTAR MAHASISWA");

        jLabel2.setText("NIM");

        jLabel3.setText("Nama");

        jLabel5.setText("Angkatan");

        jLabel6.setText("Offering");

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        tbl_mhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Prodi", "Angkatan", "Offering", "Password"
            }
        ));
        tbl_mhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_mhs);

        jLabel7.setText("Prodi");

        jLabel8.setText("Password");

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_off)
                            .addComponent(txt_pass)
                            .addComponent(txt_ang)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nim)
                                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txt_prodi, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addGap(0, 124, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(79, 79, 79)
                            .addComponent(btn_simpan)
                            .addGap(18, 18, 18)
                            .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_hapus)
                            .addGap(18, 18, 18)
                            .addComponent(btn_reset)
                            .addGap(69, 69, 69))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_prodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_ang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_off, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_simpan)
                    .addComponent(btn_edit)
                    .addComponent(btn_hapus)
                    .addComponent(btn_reset))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        if(txt_nim.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, NIM belum diisi!");
            txt_nim.requestFocus();
        }else if(txt_nama.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Nama belum diisi!");
            txt_nama.requestFocus();
        }else if(txt_prodi.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Program Studi belum diisi!");
            txt_prodi.requestFocus();
        }else if(txt_ang.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Angkatan belum diisi!");
            txt_ang.requestFocus();
        }else if(txt_off.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Offering belum diisi!");
            txt_off.requestFocus();
        }else if(txt_pass.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Password belum diisi!");
            txt_pass.requestFocus();
        }else {
            String nim = "", nama = "", prodi = "", angkatan = "", off = "", pass = "";
            try {
                mhs.setNim(txt_nim.getText());
                mhs.setNama(txt_nama.getText());
                mhs.setProdi(txt_prodi.getText());
                mhs.setAng(txt_ang.getText());
                mhs.setOff(txt_off.getText());
                mhs.setPass(txt_pass.getText());
                
                mhs.ubahData(mhs.getNim(), mhs.getNama(), mhs.getProdi(), mhs.getAng(), mhs.getOff(), mhs.getPass());
                
                JOptionPane.showMessageDialog(null, "Data berhasil diubah" , "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal diubah","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset_text();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        if(txt_nim.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, NIM belum diisi!");
            txt_nim.requestFocus();
        }else if(txt_nama.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Nama belum diisi!");
            txt_nama.requestFocus();
        }else if(txt_prodi.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Program Studi belum diisi!");
            txt_prodi.requestFocus();
        }else if(txt_ang.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Angkatan belum diisi!");
            txt_ang.requestFocus();
        }else if(txt_off.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Offering belum diisi!");
            txt_off.requestFocus();
        }else if(txt_pass.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Password belum diisi!");
            txt_pass.requestFocus();
        }else {
            String nim = "", nama = "", prodi = "", angkatan = "", off = "", pass = "";
            try {
                mhs.setNama(txt_nama.getText());
                mhs.setProdi(txt_prodi.getText());
                mhs.setAng(txt_ang.getText());
                mhs.setOff(txt_off.getText());
                mhs.setPass(txt_pass.getText());
                mhs.setNim(txt_nim.getText());
                
                mhs.simpanData(mhs.getNim(), mhs.getNama(), mhs.getProdi(), mhs.getAng(), mhs.getOff(), mhs.getPass());
                
                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan" , "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal tersimpan","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        if(txt_nim.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, NIM belum diisi!");
            txt_nim.requestFocus();
        } else {
            if(JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data ini ?",
                    "Warning",2)==JOptionPane.YES_OPTION){
                String nim = "";
                try {
                    mhs.setNim(txt_nim.getText());
                    mhs.hapusData(mhs.getNim());
                    
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus" , "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                    tampil_database();
                    reset_text();
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tbl_mhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mhsMouseClicked
        try {
            int row = tbl_mhs.rowAtPoint(evt.getPoint());
            
            String nim = tbl_mhs.getValueAt(row, 0).toString();
            String nama = tbl_mhs.getValueAt(row, 1).toString();
            String prodi = tbl_mhs.getValueAt(row, 2).toString();
            String angkatan = tbl_mhs.getValueAt(row, 3).toString();
            String off = tbl_mhs.getValueAt(row, 4).toString();
            String pass = tbl_mhs.getValueAt(row, 5).toString();
            
            txt_nim.setText(String.valueOf(nim));
            txt_nama.setText(String.valueOf(nama));
            txt_prodi.setText(String.valueOf(prodi));
            txt_ang.setText(String.valueOf(angkatan));
            txt_off.setText(String.valueOf(off));
            txt_pass.setText(String.valueOf(pass));
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_tbl_mhsMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Beranda_admin n = new Beranda_admin();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_mhs;
    private javax.swing.JTextField txt_ang;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nim;
    private javax.swing.JTextField txt_off;
    private javax.swing.JTextField txt_pass;
    private javax.swing.JTextField txt_prodi;
    // End of variables declaration//GEN-END:variables
}
