package media.interaktif;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Pilgan extends javax.swing.JFrame {
    private DefaultTableModel tabmode;
    private ResultSet hasil;
    
    CRUDpilgan pilgan = new CRUDpilgan();
    CRUDjawab jwb = new CRUDjawab();
    
    public Pilgan() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void tampil_database1(){
        Object[]baris = {"materi", "kode_soal","urutan", "soal", "pilihan_a", "pilihan_b","pilihan_c","pilihan_d"};
        tabmode = new DefaultTableModel(null, baris);
        tbl_pilgan.setModel(tabmode);
        try{
            hasil = pilgan.tampilData1();
            while(hasil.next()){
                pilgan.setMateri(hasil.getString("materi"));
                pilgan.setKode(hasil.getString("kode_soal"));
                pilgan.setUrutan(hasil.getInt("urutan"));
                pilgan.setSoal(hasil.getString("soal"));
                pilgan.setPA(hasil.getString("pilihan_a"));
                pilgan.setPB(hasil.getString("pilihan_b"));
                pilgan.setPC(hasil.getString("pilihan_c"));
                pilgan.setPD(hasil.getString("pilihan_d"));
                Object[] data = {pilgan.getMateri(), pilgan.getKode(), pilgan.getUrutan(), pilgan.getSoal(), pilgan.getPA(), 
                    pilgan.getPB(), pilgan.getPC(), pilgan.getPD()};
                tabmode.addRow(data);
            } 
        } catch(Exception e){
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cb_pilih = new javax.swing.JComboBox();
        btn_ok = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_submit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_kembali = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_pilgan = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pilgan = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_pilgan1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_pilgan3 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_pilgan2 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        ta_pilgan4 = new javax.swing.JTextArea();
        jwb_1 = new javax.swing.JTextField();
        jwb_2 = new javax.swing.JTextField();
        jwb_3 = new javax.swing.JTextField();
        jwb_4 = new javax.swing.JTextField();
        jwb_5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel2.setText("Pilihan Materi");

        cb_pilih.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enkapsulasi", "Abstract Class", "Interface", "Polymorphism" }));

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        jLabel8.setText("5.");

        jLabel7.setText("3. ");

        jLabel4.setText("1. ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Pilihan Jawaban");

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        jLabel5.setText("2.");

        jLabel6.setText("4.");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("PILIHAN GANDA");

        cb_kembali.setText("Kembali");
        cb_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kembaliActionPerformed(evt);
            }
        });

        ta_pilgan.setColumns(20);
        ta_pilgan.setRows(5);
        jScrollPane3.setViewportView(ta_pilgan);

        tbl_pilgan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pilganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pilgan);

        ta_pilgan1.setColumns(20);
        ta_pilgan1.setRows(5);
        jScrollPane4.setViewportView(ta_pilgan1);

        ta_pilgan3.setColumns(20);
        ta_pilgan3.setRows(5);
        jScrollPane5.setViewportView(ta_pilgan3);

        ta_pilgan2.setColumns(20);
        ta_pilgan2.setRows(5);
        jScrollPane6.setViewportView(ta_pilgan2);

        ta_pilgan4.setColumns(20);
        ta_pilgan4.setRows(5);
        jScrollPane7.setViewportView(ta_pilgan4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cb_kembali)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cb_pilih, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ok))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(296, 296, 296)
                                .addComponent(jLabel9)))
                        .addGap(257, 257, 257)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jwb_2)
                                                .addComponent(jwb_1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jwb_3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jwb_4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_submit)
                                            .addComponent(jwb_5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_pilih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jwb_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jwb_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jwb_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jwb_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jwb_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(btn_submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_kembali)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(69, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_kembaliActionPerformed
        // TODO add your handling code here:
        Beranda n = new Beranda();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cb_kembaliActionPerformed

    private void tbl_pilganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pilganMouseClicked
        try {
            int row = tbl_pilgan.rowAtPoint(evt.getPoint());
            
            String materi = tbl_pilgan.getValueAt(row, 0).toString();
            String kode_soal = tbl_pilgan.getValueAt(row, 1).toString();
            String urutan = tbl_pilgan.getValueAt(row, 2).toString();
            String soal = tbl_pilgan.getValueAt(row, 3).toString();
            String pilihan_a = tbl_pilgan.getValueAt(row, 4).toString();
            String pilihan_b = tbl_pilgan.getValueAt(row, 5).toString();
            String pilihan_c = tbl_pilgan.getValueAt(row, 6).toString();
            String pilihan_d = tbl_pilgan.getValueAt(row, 7).toString();
            
            ta_pilgan.setText(String.valueOf(soal));
            ta_pilgan1.setText(String.valueOf(pilihan_a));
            ta_pilgan2.setText(String.valueOf(pilihan_b));
            ta_pilgan3.setText(String.valueOf(pilihan_c));
            ta_pilgan4.setText(String.valueOf(pilihan_d));

        } catch(Exception e){

        }
    }//GEN-LAST:event_tbl_pilganMouseClicked

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        String mtr = (String)cb_pilih.getSelectedItem();
        if(mtr=="Enkapsulasi"){
            Object[]baris = {"materi", "kode_soal","urutan", "soal", "pilihan_a", "pilihan_b","pilihan_c","pilihan_d"};
            tabmode = new DefaultTableModel(null, baris);
            tbl_pilgan.setModel(tabmode);
            try{
                hasil = pilgan.tampilData1();
                while(hasil.next()){
                    pilgan.setMateri(hasil.getString("materi"));
                    pilgan.setKode(hasil.getString("kode_soal"));
                    pilgan.setUrutan(hasil.getInt("urutan"));
                    pilgan.setSoal(hasil.getString("soal"));
                    pilgan.setPA(hasil.getString("pilihan_a"));
                    pilgan.setPB(hasil.getString("pilihan_b"));
                    pilgan.setPC(hasil.getString("pilihan_c"));
                    pilgan.setPD(hasil.getString("pilihan_d"));
                    Object[] data = {pilgan.getMateri(), pilgan.getKode(), pilgan.getUrutan(), pilgan.getSoal(), pilgan.getPA(), 
                        pilgan.getPB(), pilgan.getPC(), pilgan.getPD()};
                    tabmode.addRow(data);
                } 
            } catch(Exception e){
            }
        }else if(mtr=="Abstract Class"){
            Object[]baris = {"materi", "kode_soal","urutan", "soal", "pilihan_a", "pilihan_b","pilihan_c","pilihan_d"};
            tabmode = new DefaultTableModel(null, baris);
            tbl_pilgan.setModel(tabmode);
            try{
                hasil = pilgan.tampilData2();
                while(hasil.next()){
                    pilgan.setMateri(hasil.getString("materi"));
                    pilgan.setKode(hasil.getString("kode_soal"));
                    pilgan.setUrutan(hasil.getInt("urutan"));
                    pilgan.setSoal(hasil.getString("soal"));
                    pilgan.setPA(hasil.getString("pilihan_a"));
                    pilgan.setPB(hasil.getString("pilihan_b"));
                    pilgan.setPC(hasil.getString("pilihan_c"));
                    pilgan.setPD(hasil.getString("pilihan_d"));
                    Object[] data = {pilgan.getMateri(), pilgan.getKode(), pilgan.getUrutan(), pilgan.getSoal(), pilgan.getPA(), 
                        pilgan.getPB(), pilgan.getPC(), pilgan.getPD()};
                    tabmode.addRow(data);
                } 
            } catch(Exception e){
            }
        }else {
            System.out.println("error");
        }
    }//GEN-LAST:event_btn_okActionPerformed

    public void reset_text(){
        jwb_1.setText("");
        jwb_2.setText("");
        jwb_3.setText("");
        jwb_4.setText("");
        jwb_5.setText("");
    }
    
    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        if(jwb_1.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, nomor 1 belum diisi!");
            jwb_1.requestFocus();
        }else if(jwb_2.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, nomor 2 diisi!");
            jwb_2.requestFocus();
        }else if(jwb_3.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, nomor 3 belum diisi!");
            jwb_3.requestFocus();
        }else if(jwb_4.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, nomor 4 belum diisi!");
            jwb_4.requestFocus();
        }else if(jwb_5.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, nomor 5 Password belum diisi!");
            jwb_5.requestFocus();
        }else {
            String jwb1 = "", jwb2 = "", jwb3 = "", jwb4 = "", jwb5 = "";
            try {
                jwb.setJwb1(jwb_1.getText());
                jwb.setJwb2(jwb_2.getText());
                jwb.setJwb3(jwb_3.getText());
                jwb.setJwb4(jwb_4.getText());
                jwb.setJwb5(jwb_5.getText());

                jwb.simpanData(jwb.getJwb1(), jwb.getJwb2(), jwb.getJwb3(), jwb.getJwb4(), jwb.getJwb5());

                JOptionPane.showMessageDialog(null, "Data berhasil disimpan" , "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
                reset_text();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal disimpan","Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pilgan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pilgan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pilgan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pilgan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pilgan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cb_kembali;
    private javax.swing.JComboBox cb_pilih;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jwb_1;
    private javax.swing.JTextField jwb_2;
    private javax.swing.JTextField jwb_3;
    private javax.swing.JTextField jwb_4;
    private javax.swing.JTextField jwb_5;
    private javax.swing.JTextArea ta_pilgan;
    private javax.swing.JTextArea ta_pilgan1;
    private javax.swing.JTextArea ta_pilgan2;
    private javax.swing.JTextArea ta_pilgan3;
    private javax.swing.JTextArea ta_pilgan4;
    private javax.swing.JTable tbl_pilgan;
    // End of variables declaration//GEN-END:variables
}
