package media.interaktif;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class up_materi extends javax.swing.JFrame {

    private DefaultTableModel tabmode;
    private ResultSet hasil;

    CRUDmateri materi = new CRUDmateri();
    
    public up_materi() {
        initComponents();
        tampil_database();
        setLocationRelativeTo(null);
    }
    public void tampil_database(){
        Object[]baris = {"bab", "urutan_bab", "sub_materi", "urutan_sub", "uraian"};
        tabmode = new DefaultTableModel(null, baris);
        tbl_materi.setModel(tabmode);
        try{
            hasil = materi.tampilData();
            while(hasil.next()){
                materi.setBab(hasil.getString("bab"));
                materi.setUrutanBab(hasil.getInt("urutan_bab"));
                materi.setSubMateri(hasil.getString("sub_materi"));
                materi.setUrutanSub(hasil.getInt("urutan_sub"));
                materi.setUraian(hasil.getString("uraian"));
                Object[] data = {materi.getBab(), materi.getUrutanBab(), materi.getSubMateri(), materi.getUrutanSub(), materi.getUraian()};
                tabmode.addRow(data);
            } 
        } catch(Exception e){
        }
    }
    
    public void reset_text(){
        txt_bab.setText("");
        txt_urbab.setText("");
        txt_sub.setText("");
        txt_urma.setText("");
        txt_uraian.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    } 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_bab = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_urbab = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_sub = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_urma = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_uraian = new javax.swing.JTextArea();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_materi = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bab :");

        txt_bab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_babActionPerformed(evt);
            }
        });

        jLabel3.setText("Urutan Bab :");

        txt_urbab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_urbabActionPerformed(evt);
            }
        });

        jLabel4.setText("Sub Materi :");

        jLabel5.setText("Urutan Sub Materi :");

        txt_urma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_urmaActionPerformed(evt);
            }
        });

        jLabel6.setText("Uraian :");

        txt_uraian.setColumns(20);
        txt_uraian.setRows(5);
        jScrollPane1.setViewportView(txt_uraian);

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        tbl_materi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Bab", "Urutan Bab", "Sub Materi", "Urutan Sub Materi", "Uraian"
            }
        ));
        tbl_materi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_materiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_materi);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("UPLOAD MATERI");

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(264, 264, 264))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_bab)
                            .addComponent(txt_urbab)
                            .addComponent(txt_sub)
                            .addComponent(txt_urma)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(113, 113, 113)
                                    .addComponent(btn_simpan)
                                    .addGap(23, 23, 23)
                                    .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel12)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_bab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_urbab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_urma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_babActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_babActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_babActionPerformed

    private void txt_urbabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_urbabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_urbabActionPerformed

    private void txt_urmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_urmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_urmaActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        if(txt_bab.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Bab belum diisi!");
            txt_bab.requestFocus();
        }else if(txt_urbab.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Urutan Bab belum diisi!");
            txt_urbab.requestFocus();
        }else if(txt_sub.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Sub Materi belum diisi!");
            txt_sub.requestFocus();
        }else if(txt_urma.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Urutan Sub Materi belum diisi!");
            txt_urma.requestFocus();
            
        }else if(txt_uraian.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Uraian belum diisi!");
            txt_uraian.requestFocus();
            
        }
        else {
            String bab = "", urutan_bab = "",  sub_materi = "", urutan_sub = "", uraian = "";
            try {
                materi.setBab(txt_bab.getText());
                materi.setUrutanBab(Integer.parseInt(txt_urbab.getText()));
                materi.setSubMateri(txt_sub.getText());
                materi.setUrutanSub(Integer.parseInt(txt_urma.getText()));
                materi.setUraian(txt_uraian.getText());
                
                materi.simpanData(materi.getBab(), materi.getUrutanBab(), materi.getSubMateri(), materi.getUrutanBab(), materi.getUraian());
                
                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan" , "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal tersimpan","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }      
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        if(txt_bab.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Bab belum diisi!");
            txt_bab.requestFocus();
        }else if(txt_urbab.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Urutan Bab belum diisi!");
            txt_urbab.requestFocus();
        }else if(txt_sub.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Sub Materi belum diisi!");
            txt_sub.requestFocus();
        }else if(txt_urma.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Urutan Sub Materi belum diisi!");
            txt_urma.requestFocus();
            
        }else if(txt_uraian.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Uraian belum diisi!");
            txt_uraian.requestFocus();
            
        }
        else {
            String bab = "", urutan_bab = "",  sub_materi = "", urutan_sub = "", uraian = "";
            try {
                materi.setBab(txt_bab.getText());
                materi.setUrutanBab(Integer.parseInt(txt_urbab.getText()));
                materi.setSubMateri(txt_sub.getText());
                materi.setUrutanSub(Integer.parseInt(txt_urma.getText()));
                materi.setUraian(txt_uraian.getText());
                
                materi.ubahData(materi.getBab(), materi.getUrutanBab(), materi.getSubMateri(), materi.getUrutanBab(), materi.getUraian());
                
                JOptionPane.showMessageDialog(null, "Data berhasil diubah" , "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal diubah","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        if(txt_urbab.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Urutan Bab belum diisi!");
            txt_urbab.requestFocus();
        } else {
            if(JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data ini ?",
                    "Warning",2)==JOptionPane.YES_OPTION){
                String urutan_bab = "";
                try {
                    materi.setUrutanBab(Integer.parseInt(txt_urbab.getText()));
                    materi.hapusData(materi.getUrutanBab());
                    
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus" , "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                    tampil_database();
                    reset_text();
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tbl_materiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_materiMouseClicked
        try {
            int row = tbl_materi.rowAtPoint(evt.getPoint());
            
            String bab = tbl_materi.getValueAt(row, 0).toString();
            String urutan_bab = tbl_materi.getValueAt(row, 1).toString();
            String sub_materi = tbl_materi.getValueAt(row, 2).toString();
            String urutan_sub = tbl_materi.getValueAt(row, 3).toString();
            String uraian = tbl_materi.getValueAt(row, 4).toString();
            
            txt_bab.setText(String.valueOf(bab));
            txt_urbab.setText(String.valueOf(urutan_bab));
            txt_sub.setText(String.valueOf(sub_materi));
            txt_urma.setText(String.valueOf(urutan_sub));
            txt_uraian.setText(String.valueOf(uraian));
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_tbl_materiMouseClicked

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset_text();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Beranda_dosen n = new Beranda_dosen();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(up_materi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(up_materi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(up_materi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(up_materi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new up_materi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_materi;
    private javax.swing.JTextField txt_bab;
    private javax.swing.JTextField txt_sub;
    private javax.swing.JTextArea txt_uraian;
    private javax.swing.JTextField txt_urbab;
    private javax.swing.JTextField txt_urma;
    // End of variables declaration//GEN-END:variables
}
