package media.interaktif;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class up_Pilgan extends javax.swing.JFrame {

    private DefaultTableModel tabmode;
    private ResultSet hasil;

    CRUDpilgan pilgan = new CRUDpilgan();
    
    public up_Pilgan() {
        initComponents();
        tampil_database();
        setLocationRelativeTo(null);
    }
    public void tampil_database(){
        Object[]baris = {"materi", "kode_soal",  "urutan", "soal", "pilihan_a", "pilihan_b", "pilihan_c", "pilihan_d", "kunci"};
        tabmode = new DefaultTableModel(null, baris);
        tbl_pilgan.setModel(tabmode);
        try{
            hasil = pilgan.tampilData();
            while(hasil.next()){
                pilgan.setMateri(hasil.getString("materi"));
                pilgan.setKode(hasil.getString("kode_soal"));
                pilgan.setUrutan(hasil.getInt("urutan"));
                pilgan.setSoal(hasil.getString("soal"));
                pilgan.setPA(hasil.getString("pilihan_a"));
                pilgan.setPB(hasil.getString("pilihan_b"));
                pilgan.setPC(hasil.getString("pilihan_c"));
                pilgan.setPD(hasil.getString("pilihan_d"));
                pilgan.setKunci(hasil.getString("kunci"));
                Object[] data = {pilgan.getMateri(), pilgan.getKode(), pilgan.getUrutan(), pilgan.getSoal(), pilgan.getPA(), pilgan.getPB(), pilgan.getPC(), pilgan.getPD(), pilgan.getKunci()};
                tabmode.addRow(data);
            } 
        } catch(Exception e){
        }
    }
    
    public void reset_text(){
        txt_materi.setText("");
        txt_kode.setText("");
        txt_urutan.setText("");
        txt_soal.setText("");
        txt_a.setText("");
        txt_b.setText("");
        txt_c.setText("");
        txt_d.setText("");
        txt_kunci.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    } 
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_kode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_urutan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_soal = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_a = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_b = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_c = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_d = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_kunci = new javax.swing.JTextField();
        btn_ubah = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_pilgan = new javax.swing.JTable();
        txt_materi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SOAL");

        jLabel2.setText("Materi :");

        jLabel3.setText("Kode Soal :");

        jLabel4.setText("Urutan :");

        jLabel5.setText("Soal :");

        txt_soal.setColumns(20);
        txt_soal.setRows(5);
        jScrollPane1.setViewportView(txt_soal);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("JAWABAN");

        jLabel7.setText("Pilihan A :");

        jLabel8.setText("Pilihan B :");

        txt_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bActionPerformed(evt);
            }
        });

        jLabel9.setText("Pilihan C :");

        jLabel10.setText("Pilihan D :");

        jLabel11.setText("Kunci :");

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        tbl_pilgan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Materi", "Kode Soal", "Urutan", "Soal", "Pilihan A", "Pilihan B", "Pilihan C", "Pilihan D", "Kunci"
            }
        ));
        tbl_pilgan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pilganMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_pilgan);

        txt_materi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_materiActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("UPLOAD LATIHAN PILIHAN GANDA");

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btn_simpan)
                        .addGap(31, 31, 31)
                        .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_urutan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_kode, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_materi, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_d, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_c, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_b, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_a, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_kunci, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6))
                        .addGap(49, 49, 49)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addComponent(jLabel12))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_urutan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txt_materi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txt_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txt_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_kunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        if(txt_materi.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Materi belum diisi!");
            txt_materi.requestFocus();
        }else if(txt_kode.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Kode Soal belum diisi!");
            txt_kode.requestFocus();
        }else if(txt_urutan.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Urutan belum diisi!");
            txt_urutan.requestFocus();
        }else if(txt_soal.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Soal belum diisi!");
            txt_soal.requestFocus();
        }else if(txt_a.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Pilihan A belum diisi!");
            txt_a.requestFocus();
        }else if(txt_b.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Pilihan B belum diisi!");
            txt_b.requestFocus();
        }else if(txt_c.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Pilihan C belum diisi!");
            txt_c.requestFocus();   
        }else if(txt_d.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Pilihan D belum diisi!");
            txt_d.requestFocus();   
        }else if(txt_kunci.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, kunci belum diisi!");
            txt_kunci.requestFocus();  
        }
        else {
            String materi = "", kode_soal = "", urutan="", soal = "", pilhan_a = "", pilihan_b = "", pilihan_c = "", pilihan_d = "", kunci = "";
            try {
                pilgan.setMateri(txt_materi.getText());
                pilgan.setKode(txt_kode.getText());
                pilgan.setUrutan(Integer.parseInt(txt_urutan.getText()));
                pilgan.setSoal(txt_soal.getText());
                pilgan.setPA(txt_a.getText());
                pilgan.setPB(txt_b.getText());
                pilgan.setPC(txt_c.getText());
                pilgan.setPD(txt_d.getText());
                pilgan.setKunci(txt_kunci.getText());
                
                pilgan.ubahData(pilgan.getMateri(), pilgan.getKode(), pilgan.getUrutan(), pilgan.getSoal(), pilgan.getPA(), pilgan.getPB(), pilgan.getPC(), pilgan.getPD(), pilgan.getKunci());
                
                JOptionPane.showMessageDialog(null, "Data berhasil diubah" , "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal diubah","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }                                     

    }                                        
    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {                                          
        reset_text();
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        if(txt_materi.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Materi belum diisi!");
            txt_materi.requestFocus();
        }else if(txt_kode.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Kode Soal belum diisi!");
            txt_kode.requestFocus();
        }else if(txt_urutan.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Urutan belum diisi!");
            txt_urutan.requestFocus();
        }else if(txt_soal.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Soal belum diisi!");
            txt_soal.requestFocus();
            
        }else if(txt_a.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Pilihan A belum diisi!");
            txt_a.requestFocus();
            
        }else if(txt_b.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Pilihan B belum diisi!");
            txt_b.requestFocus();
            
        }else if(txt_c.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Pilihan C belum diisi!");
            txt_c.requestFocus();
            
        }else if(txt_d.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Pilihan D belum diisi!");
            txt_d.requestFocus();
            
        }else if(txt_kunci.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, kunci belum diisi!");
            txt_kunci.requestFocus();
            
        }
        else {
            String materi = "", kode_soal = "",  urutan = "", soal = "", pilhan_a = "", pilihan_b = "", pilihan_c = "", pilihan_d = "", kunci = "";
            try {
                pilgan.setMateri(txt_materi.getText());
                pilgan.setKode(txt_kode.getText());
                pilgan.setUrutan(Integer.parseInt(txt_urutan.getText()));
                pilgan.setSoal(txt_soal.getText());
                pilgan.setPA(txt_a.getText());
                pilgan.setPB(txt_b.getText());
                pilgan.setPC(txt_c.getText());
                pilgan.setPD(txt_d.getText());
                pilgan.setKunci(txt_kunci.getText());
                
                pilgan.simpanData(pilgan.getMateri(), pilgan.getKode(), pilgan.getUrutan(), pilgan.getSoal(), pilgan.getPA(), pilgan.getPB(), pilgan.getPC(), pilgan.getPD(), pilgan.getKunci());
                
                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan" , "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal tersimpan","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }                                      

    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
         if(txt_kode.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Maaf, Kode Soal belum diisi!");
            txt_kode.requestFocus();
        } else {
            if(JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data ini ?",
                    "Warning",2)==JOptionPane.YES_OPTION){
                String kode_soal = "";
                try {
                    pilgan.setMateri(txt_kode.getText());
                   
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus" , "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                    tampil_database();
                    reset_text();
                } catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus","Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
                }
            }
            
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tbl_pilganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pilganMouseClicked
        try {
            int row = tbl_pilgan.rowAtPoint(evt.getPoint());
            
            String materi = tbl_pilgan.getValueAt(row, 0).toString();
            String kode_soal = tbl_pilgan.getValueAt(row, 1).toString();
            String urutan = tbl_pilgan.getValueAt(row, 2).toString();
            String soal = tbl_pilgan.getValueAt(row, 3).toString();
            String pilihan_a = tbl_pilgan.getValueAt(row, 4).toString();
            String pilihan_b = tbl_pilgan.getValueAt(row, 5).toString();
            String pilihan_c = tbl_pilgan.getValueAt(row, 6).toString();
            String pilihan_d = tbl_pilgan.getValueAt(row, 7).toString();
            String kunci = tbl_pilgan.getValueAt(row, 8).toString();
            
            txt_materi.setText(String.valueOf(materi));
            txt_kode.setText(String.valueOf(kode_soal));
            txt_urutan.setText(String.valueOf(urutan));
            txt_soal.setText(String.valueOf(soal));
            txt_a.setText(String.valueOf(pilihan_a));
            txt_b.setText(String.valueOf(pilihan_b));
            txt_c.setText(String.valueOf(pilihan_c));
            txt_d.setText(String.valueOf(pilihan_d));
            txt_kunci.setText(String.valueOf(kunci));
        } catch(Exception e){
            
        }
    }//GEN-LAST:event_tbl_pilganMouseClicked

    private void txt_materiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_materiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_materiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Beranda_dosen n = new Beranda_dosen();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pilgan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pilgan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pilgan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pilgan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new up_Pilgan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_pilgan;
    private javax.swing.JTextField txt_a;
    private javax.swing.JTextField txt_b;
    private javax.swing.JTextField txt_c;
    private javax.swing.JTextField txt_d;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_kunci;
    private javax.swing.JTextField txt_materi;
    private javax.swing.JTextArea txt_soal;
    private javax.swing.JTextField txt_urutan;
    // End of variables declaration//GEN-END:variables
}
